SET GLOBAL storage_engine = MyISAM;

USE FINANCAS;


/*DELETE A
FROM TB_MAPA_DATA A
INNER JOIN (SELECT DISTINCT DATA_PREGAO
FROM TB_COTACAO_HISTORICA
WHERE DATA_PREGAO IS NOT NULL
AND FL_PROCESSADO = 0
) B
WHERE A.DATA_PREGAO = B.DATA_PREGAO*/;

DROP TABLE IF EXISTS TB_MAPA_DATA;

/*INSERT INTO TB_MAPA_DATA (PERIODO, DATA_PREGAO)*/

CREATE TABLE TB_MAPA_DATA AS
SELECT DISTINCT DATA_PREGAO
FROM TB_COTACAO_HISTORICA
WHERE DATA_PREGAO IS NOT NULL
ORDER BY DATA_PREGAO;

ALTER TABLE TB_MAPA_DATA
ADD COLUMN (DATA_PREGAO_ANT DATE)
,ADD INDEX DATA_PREGAO(DATA_PREGAO)
,ADD INDEX DATA_PREGAO_ANT(DATA_PREGAO_ANT);

ALTER TABLE TB_MAPA_DATA
ADD COLUMN ID INT AUTO_INCREMENT FIRST
,ADD PRIMARY KEY(ID);

UPDATE TB_MAPA_DATA md1, TB_MAPA_DATA md2
SET md1.DATA_PREGAO_ANT = md2.DATA_PREGAO
WHERE  IF(md1.ID=1, 1, md1.ID - 1) = md2.ID
AND md1.DATA_PREGAO_ANT IS NULL;

UPDATE TB_MAPA_DATA md
, TB_COTACAO_HISTORICA ch1
, TB_COTACAO_HISTORICA ch2
SET ch1.PRECO_FECH_ANTERIOR = ch2.PRECO_ULT
, ch1.PRECO_FECH_ANTERIOR_MEDIO = ch2.PRECO_MED
WHERE ch1.data_pregao = md.Data_pregao
and md.data_pregao_ant = ch2.data_pregao
and ch1.PRAZO_TERMO = ch2.PRAZO_TERMO
AND ch1.COD_BDI = ch2.COD_BDI
AND ch1.COD_PAPEL = ch2.COD_PAPEL
AND ch1.FL_PROCESSADO = 0;

DELETE A
FROM MAPA_DATA_MES_ANT A
INNER JOIN (
SELECT DATE_ADD(ch1.PERIODO,  interval 1 month) AS PERIODO
, PRAZO_TERMO
, COD_PAPEL
, COD_BDI
, MAX(CH1.DATA_PREGAO) AS DATA_PREGAO
FROM TB_COTACAO_HISTORICA ch1
WHERE FL_PROCESSADO = 0
GROUP BY 1,2,3,4) B
ON A.PERIODO = B.PERIODO
AND A.PRAZO_TERMO = B.PRAZO_TERMO
AND A.COD_PAPEL = B.COD_PAPEL
AND A.COD_BDI = B.COD_BDI;

INSERT INTO MAPA_DATA_MES_ANT
SELECT DATE_ADD(ch1.PERIODO,  interval 1 month) AS PERIODO
, PRAZO_TERMO
, COD_PAPEL
, COD_BDI
, MAX(CH1.DATA_PREGAO) AS DATA_PREGAO
FROM TB_COTACAO_HISTORICA ch1
WHERE FL_PROCESSADO = 0
GROUP BY 1,2,3,4;

DELETE FROM MAPA_DATA_MES_ANT
WHERE PERIODO = '2019-01-01';

INSERT INTO MAPA_DATA_MES_ANT
SELECT PERIODO
, PRAZO_TERMO
, COD_PAPEL
, COD_BDI
, MIN(CH1.DATA_PREGAO) AS DATA_PREGAO
FROM TB_COTACAO_HISTORICA ch1
WHERE PERIODO = '2019-01-01'
GROUP BY 1,2,3,4;

/*ALTER TABLE MAPA_DATA_MES_ANT
ADD INDEX DATA_INDEX(DATA_PREGAO, COD_BDI, COD_PAPEL, PRAZO_TERMO)
, ADD INDEX PERIODO_INDEX(PERIODO, COD_BDI, COD_PAPEL, PRAZO_TERMO)*/
;

UPDATE TB_COTACAO_HISTORICA ch1
, MAPA_DATA_MES_ANT md
, TB_COTACAO_HISTORICA ch2
SET ch1.PRECO_FECH_MES_ANTERIOR = ch2.PRECO_ULT
, ch1.PRECO_FECH_MES_ANTERIOR_MEDIO = ch2.PRECO_MED
WHERE ch1.periodo = md.periodo
and ch1.PRAZO_TERMO = md.PRAZO_TERMO
AND ch1.COD_PAPEL = md.COD_PAPEL
AND ch1.COD_BDI = md.COD_BDI
and md.data_pregao = ch2.data_pregao
and md.PRAZO_TERMO = ch2.PRAZO_TERMO
AND md.COD_PAPEL = ch2.COD_PAPEL
AND md.COD_BDI = ch2.COD_BDI
AND ch1.FL_PROCESSADO = 0;

DROP TABLE IF EXISTS MAPA_DATA_CORTE;

CREATE TABLE IF NOT EXISTS MAPA_DATA_CORTE
SELECT MAX(CH1.DATA_PREGAO) AS DATA_PREGAO
FROM TB_COTACAO_HISTORICA ch1;

DROP TABLE IF EXISTS MAPA_DATA_30D;

CREATE TABLE IF NOT EXISTS MAPA_DATA_30D
SELECT PRAZO_TERMO
, COD_PAPEL
, COD_BDI
, MIN(CH1.DATA_PREGAO) AS DATA_PREGAO
FROM TB_COTACAO_HISTORICA ch1
WHERE CH1.DATA_PREGAO BETWEEN DATE_ADD((select data_pregao from MAPA_DATA_CORTE), INTERVAL -31 DAY) AND (select data_pregao from MAPA_DATA_CORTE)
GROUP BY 1,2,3;

ALTER TABLE MAPA_DATA_30D
ADD INDEX CINDEX_30D(PRAZO_TERMO, COD_PAPEL, COD_BDI, DATA_PREGAO);

UPDATE TB_COTACAO_HISTORICA ch1
, MAPA_DATA_30D md
, TB_COTACAO_HISTORICA ch2
SET ch1.PRECO_FECH_30D = ch2.PRECO_ULT
, ch1.PRECO_FECH_30D_MEDIO = ch2.PRECO_MED
WHERE ch1.DATA_PREGAO = (SELECT DATA_PREGAO FROM MAPA_DATA_CORTE)
and ch1.PRAZO_TERMO = md.PRAZO_TERMO
AND ch1.COD_PAPEL = md.COD_PAPEL
AND ch1.COD_BDI = md.COD_BDI
and md.data_pregao = ch2.data_pregao
and md.PRAZO_TERMO = ch2.PRAZO_TERMO
AND md.COD_PAPEL = ch2.COD_PAPEL
AND md.COD_BDI = ch2.COD_BDI;


DROP TABLE IF EXISTS MAPA_DATA_7D;

CREATE TABLE IF NOT EXISTS MAPA_DATA_7D
SELECT PRAZO_TERMO
, COD_PAPEL
, COD_BDI
, MIN(CH1.DATA_PREGAO) AS DATA_PREGAO
FROM TB_COTACAO_HISTORICA ch1
WHERE CH1.DATA_PREGAO BETWEEN DATE_ADD((select data_pregao from MAPA_DATA_CORTE), INTERVAL -7 DAY) AND (select data_pregao from MAPA_DATA_CORTE)
GROUP BY 1,2,3;

ALTER TABLE MAPA_DATA_7D
ADD INDEX CINDEX_30D(PRAZO_TERMO, COD_PAPEL, COD_BDI, DATA_PREGAO);

UPDATE TB_COTACAO_HISTORICA ch1
, MAPA_DATA_7D md
, TB_COTACAO_HISTORICA ch2
SET ch1.PRECO_FECH_SEM_ANTERIOR = ch2.PRECO_ULT
, ch1.PRECO_FECH_SEM_ANTERIOR_MEDIO = ch2.PRECO_MED
WHERE ch1.DATA_PREGAO = (SELECT DATA_PREGAO FROM MAPA_DATA_CORTE)
and ch1.PRAZO_TERMO = md.PRAZO_TERMO
AND ch1.COD_PAPEL = md.COD_PAPEL
AND ch1.COD_BDI = md.COD_BDI
and md.data_pregao = ch2.data_pregao
and md.PRAZO_TERMO = ch2.PRAZO_TERMO
AND md.COD_PAPEL = ch2.COD_PAPEL
AND md.COD_BDI = ch2.COD_BDI;

DROP TABLE IF EXISTS MAPA_DATA_INI_ANO;

CREATE TABLE IF NOT EXISTS MAPA_DATA_INI_ANO AS
SELECT PRAZO_TERMO
, COD_PAPEL
, COD_BDI
, MIN(CH1.DATA_PREGAO) AS DATA_PREGAO
FROM TB_COTACAO_HISTORICA ch1
GROUP BY 1,2,3;

ALTER TABLE MAPA_DATA_INI_ANO
ADD INDEX DATA_INDEX(DATA_PREGAO, COD_BDI, COD_PAPEL, PRAZO_TERMO);

UPDATE TB_COTACAO_HISTORICA ch1
, MAPA_DATA_INI_ANO md
, TB_COTACAO_HISTORICA ch2
SET ch1.PRECO_INI_ANO = ch2.PRECO_ABER
, ch1.PRECO_INI_ANO_MEDIO = ch2.PRECO_MED
WHERE ch1.PRAZO_TERMO = md.PRAZO_TERMO
AND ch1.COD_PAPEL = md.COD_PAPEL
AND ch1.COD_BDI = md.COD_BDI
AND md.data_pregao = ch2.data_pregao
AND md.PRAZO_TERMO = ch2.PRAZO_TERMO
AND md.COD_PAPEL = ch2.COD_PAPEL
AND md.COD_BDI = ch2.COD_BDI
AND ch1.FL_PROCESSADO = 0;

UPDATE TB_COTACAO_HISTORICA
SET FL_PROCESSADO = 1
WHERE FL_PROCESSADO = 0;